updates 2024

diff --git a/zshrc-github b/zshrc-github
--- a/zshrc-github
+++ b/zshrc-github
@@ -4,6 +4,8 @@
 # Path to your oh-my-zsh installation.
 export ZSH="/Users/Josh/.oh-my-zsh"
 
+
+
 # Set name of the theme to load. Optionally, if you set this to "random"
 # it'll load a random theme each time that oh-my-zsh is loaded.
 # See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
@@ -66,25 +68,84 @@ plugins=(
   dotenv
   osx
   rbenv
+  pyenv
+  ssh-agent
 )
+### IMPORTANT: put these settings before the line that sources oh-my-zsh
+zstyle :omz:plugins:ssh-agent agent-forwarding yes
+zstyle ':omz:plugins:ssh-agent' identities id_rsa josh_key_pair.pem everfi20210621
+#### END IMPORTANT
 
 source $ZSH/oh-my-zsh.sh
 
 # User configuration
 export EDITOR='vim'
-export PATH=/usr/local/bin:$PATH:/opt/nginx/sbin:$HOME/bin
+export PATH=/usr/local/bin:$HOME/bin:$PATH
 export AWS_REGION=us-east-1
 export PATH="/Users/Josh/miniconda3/bin:$PATH"
 export GITHUB_TOKEN= #redacted
 export JIRA_TOKEN= #redacted
 
-export PATH="/usr/local/opt/postgresql@9.6/bin:/usr/local/lib/node_modules:$PATH"
+function p { for f in $(ls -d ~/projects/$1*); do cd $f; break; done; }
+export PATH="/usr/local/lib/node_modules:$PATH"
 export AWS_DEFAULT_REGION=us-east-1
 export PYENV_ROOT=$(pyenv root)
 export PIPENV_PYTHON=$PYENV_ROOT/shims/python
-function p { for f in $(ls -d ~/projects/$1*); do cd $f; break; done; }
 alias git_add_modified="git status | grep 'modified' | ruby -e \"puts STDIN.read.gsub(/.*:/,'').gsub(/\n/,'')\" | xargs git add"
-#alias get_emr_master="AWS_PROFILE=jstanfield pipenv run aws emr list-instances --cluster-id $(AWS_DEFAULT_OUTPUT=json AWS_PROFILE=jstanfield pipenv run aws emr list-clusters --active | jq -c -M -r '.Clusters[].Id') --instance-group-type MASTER"
+
+eval "$(pyenv init -)"
+
+
+
+########## TAB COMPLETION FOR VARIOUS NODE PACKAGES ##########
+## tabtab source for serverless package
+## uninstall by removing these lines or running `tabtab uninstall serverless`
+#[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
+## tabtab source for sls package
+## uninstall by removing these lines or running `tabtab uninstall sls`
+#[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
+#eval "$(rbenv init -)"
+#stty -ixon
+#
+## tabtab source for slss package
+## uninstall by removing these lines or running `tabtab uninstall slss`
+#[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh
+######## END TAB COMPLETION STUFF ##########
+#
+
+HISTFILE=~/.zsh_history
+HISTSIZE=999999999
+SAVEHIST=$HISTSIZE
+setopt hist_ignore_all_dups
+setopt hist_ignore_space
+setopt HIST_EXPIRE_DUPS_FIRST
+
+[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
+bindkey '^T' transpose-chars
+alias ll="ls -larth"
+
+
+
+
+###########NVM STUFF ############
+#export NVM_DIR=/Users/jstanfield/.nvm
+#
+## Shim NVM that will load the real NVM.
+## Saves 800ms of script start-up time.
+#function nvm() {
+#  if [[ ! -e "${NVM_DIR}/nvm.sh" ]]; then
+#    echo "NVM not found in NVM_DIR=${NVM_DIR}" >&2
+#    return 1
+#  fi
+#
+#  unfunction nvm
+#  source "${NVM_DIR}/nvm.sh"
+#  nvm "$@"
+#}
+
+########## END NVM STUFF ##########
+
+
 
 eval "$(pyenv init -)"
 
